LabSystem/LabSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Labs.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LabSystem/Labs/urls.py
from os import name
from . import views
from django.urls import path

app_name = 'Labs'

urlpatterns = [
    path('', views.index, name='index'),
    path('register_tester/', views.register_tester, name='register_tester'),
    path('tester_list/', views.tester_list, name='tester_list'),
    path('tester_details/<int:pk>/', views.tenant_details, name='tester_details'),
    path('delete_tester/<int:pk>/', views.delete_tester, name='delete_tester'),

    #patients
    path('register_patient', views.register_patient, name='register_patient'),
    path('patient_list', views.patient_list, name='patient_list'),
    path('patients_details/<int:pk>/', views.patients_details, name='patients_details'),
    path('delete_patient/<int:pk>/', views.delete_patient, name='delete_patient'),

    #samples
    path('register_sample/', views.register_sample, name='register_sample'),
    path('sample_list/', views.sample_list, name='sample_list'),
    path('update_sample_result/<int:pk>/', views.update_sample_result, name='update_sample_result'),

    #vaccination
    path('register_vaccination/', views.register_vaccination, name='register_vaccination'),
    path('vaccination_list/', views.vaccination_list, name='vaccination_list'),

    #authentication
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user', views.logout_user, name='logout_user'),
    path('register_user/', views.register, name='register'),

    #reports
    path('infection_per_county/', views.infection_per_county, name='infection_per_county'),
    path('infection_per_county/<str:county>/', views.infection_per_county_detail, name='infection_per_county_detail')
]

LabSystem/Labs/models.py
from django.db import models
from django.contrib.auth.models import User


class LabCenter(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    lab_name = models.CharField(max_length=50)
    location = models.CharField(max_length=50)
    remaining_testing_kits = models.IntegerField(default=0)
    remaining_vaccines = models.IntegerField(default=0)


professionChoice = (
    ('Doctor', 'Doctor'),
    ('Nurse', 'Nurse'),
    ('Regular', 'Regular'),
)


class Tester(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    gender = models.CharField(max_length=10)
    id_number = models.CharField(max_length=10)
    contact = models.CharField(max_length=10)
    email = models.CharField(max_length=100)
    profession = models.CharField(max_length=100, choices=professionChoice)
    avatar = models.ImageField()

    class Meta:
        verbose_name = 'Tester'
        verbose_name_plural = 'Testers'

    def __str__(self):
        return self.first_name


class Patient(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    gender = models.CharField(max_length=10)
    id_number = models.CharField(max_length=10, blank=True, null=True)
    contact = models.CharField(max_length=10)
    email = models.CharField(max_length=100)
    region = models.CharField(max_length=100)
    county = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    last_status = models.CharField(max_length=20, null=True, blank=True)

    class Meta:

        verbose_name = 'Patient'
        verbose_name_plural = 'Patients'

    def __str__(self):
        return self.first_name + ' ' + self.last_name


resultStatus = (
    ('Positive', 'Positive'),
    ('Negative', 'Negative')
)


class Specimen(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    Ref_code = models.CharField(max_length=10000, blank=True, null=True)
    date_taken = models.DateField(auto_now_add=True)
    processed = models.BooleanField(default=False)
    results = models.CharField(max_length=20, choices=resultStatus, blank=True, null=True)

    class Meta:

        verbose_name = 'Specimen'
        verbose_name_plural = 'Specimens'

    def __str__(self):
        return str(self.Ref_code)


FirstSecondChoice = (
    ('First', 'First'),
    ('Second', 'Second')
)


class Vaccination(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    date_of_administration = models.DateTimeField(auto_now_add=True)
    first_or_second = models.CharField(
        max_length=20, choices=FirstSecondChoice, blank=True, null=True)

    class Meta:

        verbose_name = 'Vaccination'
        verbose_name_plural = 'Vaccinations'

    def __str__(self):
        return str(self.pk)


class VaccinationKitSupply(models.Model):
    delivery_sn_no = models.CharField(max_length=1000)
    number_of_kits = models.IntegerField(default=0)
    date_of_delivery = models.DateField()

    class Meta:

        verbose_name = 'VaccinationKit'
        verbose_name_plural = 'VaccinationKits'

    def __str__(self):
        return self.delivery_sn_no
    

LabSystem/Labs/forms.py
from django import forms
from django.forms import fields, widgets
from .models import *

class RegisterTester(forms.ModelForm):
    class Meta:
        model = Tester
        fields = '__all__'


class RegisterPatient(forms.ModelForm):
    class Meta:
        model = Patient
        fields = '__all__'


class RegisterSample(forms.ModelForm):
    class Meta:
        model = Specimen
        fields = '__all__'

        widgets = {
            'patient': forms.Select(attrs={'class': 'form-control form-control-select2', 'required':'True','name':'patient', 'placeholder': 'patient'}),
        }

class RegisterVaccination(forms.ModelForm):
    class Meta:
        model = Vaccination
        fields = '__all__'

        widgets = {
            'patient': forms.Select(attrs={'class': 'form-control form-control-select2', 'required':'True','name':'patient', 'placeholder': 'patient'}),
        }

class UserLogForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class LabCenterForm(forms.ModelForm):
    class Meta:
        model = LabCenter
        fields = '__all__'

LabSystem/Labs/views.py
from collections import Counter
from django import contrib
import django
from django.core.exceptions import ObjectDoesNotExist
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import *
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from datetime import datetime, timedelta
from .models import *


def index(request):
    testers = Tester.objects.all().count()
    patients = Patient.objects.all().count()
    samples = Specimen.objects.all().count()
    vaccinations = Vaccination.objects.all().count()

    today_date = datetime.today()
    monthly_model = Specimen.objects.filter(
        date_taken__month=today_date.month, results='Positive').values_list("date_taken")
    monthly_count_rep = Counter([rep[0] for rep in monthly_model])
    monthly_amount_rep = {}

    for rep in monthly_count_rep:
        monthly_amount_rep[rep] = 0

    for month in monthly_model:
        for rep in monthly_amount_rep:
            if month[0] == rep:
                monthly_amount_rep[rep] += 1

    label = list(monthly_amount_rep.keys())
    data = list(monthly_amount_rep.values())

    monthly_model2 = Specimen.objects.filter(
        date_taken__month=today_date.month, results='Negative').values_list("date_taken")
    monthly_count_rep2 = Counter([rep[0] for rep in monthly_model2])
    monthly_amount_rep2 = {}

    for rep2 in monthly_count_rep2:
        monthly_amount_rep2[rep2] = 0

    for month in monthly_model2:
        for rep2 in monthly_amount_rep2:
            if month[0] == rep2:
                monthly_amount_rep2[rep2] += 1
    data2 = list(monthly_amount_rep2.values())

    # compute infection per county

    county_model = Specimen.objects.filter(
        date_taken__month=today_date.month, results='Positive').values_list("patient__county")
    county_count_rep = Counter([rep[0] for rep in county_model])
    county_amount_rep = {}

    for rep in county_count_rep:
        county_amount_rep[rep] = 0

    for month in county_model:
        for rep in county_amount_rep:
            if month[0] == rep:
                county_amount_rep[rep] += 1

    label3 = list(county_amount_rep.keys())
    data3 = list(county_amount_rep.values())

    context = {
        'label': label,
        'data': data,
        'data2': data2,
        'label3': label3,
        'data3': data3,
        'testers': testers,
        'patients': patients,
        'samples': samples,
        'vaccinations': vaccinations
    }
    return render(request, 'Labs/dashboard.html', context)


def register_tester(request):

    if request.method == 'GET':
        return render(request, 'Labs/register_tester.html')

    if request.method == 'POST':
        form = RegisterTester(request.POST or None, request.FILES)

        if form.is_valid():
            first_name = form.data['first_name']
            last_name = form.data['last_name']
            gender = form.data['gender']
            id_number = form.data['id_number']
            contact = form.data['contact']
            email = form.data['email']
            profession = form.data['profession']
            avatar = request.FILES['avatar']

            try:
                from PIL import Image
                Image.open(avatar)
            except:
                from django.contrib import messages
                messages.warning(request, 'Sorry your image is invalid')
                return redirect('Labs:index')

            Tester.objects.create(
                user=request.user,
                first_name=first_name.capitalize(),
                last_name=last_name.capitalize(),
                gender=gender,
                id_number=id_number,
                contact=contact,
                email=email,
                profession=profession,
                avatar=avatar,
            )
            from django.contrib import messages
            messages.success(request, 'Tester created Successfully.')
            return redirect('Labs:index')
        else:
            print(form.errors)
            from django.contrib import messages
            messages.warning(
                request, 'An error occurred. Try again later or contact the administrator.')
            return redirect('Labs:index')


def tester_list(request):

    all_testers = Tester.objects.filter(user=request.user)
    context = {
        'all_testers': all_testers,
    }
    return render(request, 'Labs/tester_list.html', context)


def tenant_details(request, pk):
    tester = Tester.objects.get(id=pk)
    context = {
        'tester': tester
    }
    return render(request, 'Labs/tester_details.html', context)


def delete_tester(request, pk):
    tester = Tester.objects.get(id=pk)

    tester.delete()
    messages.success(request, 'Tester record deleted successfully')
    return redirect('Labs:index')


def register_patient(request):

    if request.method == 'GET':
        return render(request, 'Labs/register_patient.html')

    if request.method == 'POST':
        form = RegisterPatient(request.POST or None)

        if form.is_valid():

            first_name = form.data['first_name']
            last_name = form.data['last_name']
            gender = form.data['gender']
            id_number = form.data['id_number']
            contact = form.data['contact']
            email = form.data['email']
            region = form.data['region']
            county = form.data['county']
            user = request.user
            location = form.data['location']

            all_patients = Patient.objects.all()

            for patient in all_patients:
                if id_number != '' and patient.id_number == id_number:
                    from django.contrib import messages
                    messages.warning(
                        request, 'Sorry, Patient with this Id Number is already Registered.')
                    return redirect('Labs:register_patient')

            Patient.objects.create(
                user=user,
                first_name=first_name.capitalize(),
                last_name=last_name.capitalize(),
                gender=gender,
                id_number=id_number,
                contact=contact,
                email=email,
                region=region,
                county=county,
                location=location,
            )
            from django.contrib import messages
            messages.success(request, 'Patient created Successfully.')
            return redirect('Labs:index')
        else:
            print(form.errors)
            from django.contrib import messages
            messages.warning(
                request, 'An error occurred. Try again later or contact the administrator.')
            return redirect('Labs:index')


def patient_list(request):
    all_patients = Patient.objects.filter(user=request.user)
    context = {
        'all_patients': all_patients,
    }
    return render(request, 'Labs/patient_list.html', context)


def patients_details(request, pk):
    patient = Patient.objects.get(id=pk)

    previous_testings = Specimen.objects.filter(patient=patient)
    previous_vaccinations = Vaccination.objects.filter(patient=patient)
    context = {
        'patient': patient,
        'previous_testings': previous_testings,
        'previous_vaccinations': previous_vaccinations,
    }
    return render(request, 'Labs/patient_details.html', context)


def delete_patient(request, pk):
    patient = Patient.objects.get(id=pk)
    patient.delete()
    messages.success(request, 'The patient was deleted successfully.')
    return redirect('Labs:index')


def register_sample(request):

    if request.method == 'GET':
        form = RegisterSample(request.POST or None)
        context = {
            'form': form
        }
        return render(request, 'Labs/register_sample.html', context)

    if request.method == 'POST':
        form = RegisterSample(request.POST or None)

        if form.is_valid():
            patient = form.data['patient']
            patient = Patient.objects.get(id=patient)
            ref_code = form.data['ref_code']

            all_samples = Specimen.objects.all()

            for sample in all_samples:
                if ref_code != '' and sample.Ref_code == ref_code:
                    from django.contrib import messages
                    messages.warning(
                        request, 'Sorry, Sample with this ID is already Registered.')
                    return redirect('Labs:register_sample')

            Specimen.objects.create(
                user=request.user,
                patient=patient,
                Ref_code=ref_code,
            )
            from django.contrib import messages
            messages.success(request, 'Sample created Successfully.')
            return redirect('Labs:index')
        else:
            print(form.errors)
            from django.contrib import messages
            messages.warning(
                request, 'An error occurred. Try again later or contact the administrator.')
            return redirect('Labs:index')


def sample_list(request):
    unprocessed_samples = Specimen.objects.filter(
        processed=False, user=request.user)
    processed_samples = Specimen.objects.filter(
        processed=True, user=request.user)

    context = {
        'unprocessed_samples': unprocessed_samples,
        'processed_samples': processed_samples,

    }
    return render(request, 'Labs/sample_list.html', context)


def update_sample_result(request, pk):
    sample = Specimen.objects.get(id=pk)

    result = request.POST.get('result')

    sample.results = result
    sample.processed = True
    sample.save()
    sample.patient.last_status = result
    sample.patient.save()

    messages.success(request, 'Sample status updated Successfully.')

    return redirect('Labs:sample_list')


def register_vaccination(request):

    if request.method == 'GET':

LabSystem/Labs/templates/Labs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Covid-19 System</title>
	{% load static %}
	<!-- Global stylesheets -->
	<link rel="shortcut icon" href="{% static 'Labs/images/logo.png' %}" type="image/x-icon">
	<link href="{% static 'Labs/global_assets/css/icons/icomoon/styles.min.css ' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'Labs/assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'Labs/assets/css/bootstrap_limitless.min.css  '%}" rel="stylesheet" type="text/css">
	<link href="{% static 'Labs/assets/css/layout.min.css'%}" rel="stylesheet" type="text/css">
	<link href="{% static 'Labs/assets/css/components.min.css '%}" rel="stylesheet" type="text/css">
	<link href="{% static 'Labs/assets/css/colors.min.css '%}" rel="stylesheet" type="text/css">
	<link href="{% static 'Labs/fontawesome-free/css/all.css'%}" rel="stylesheet" type="text/css">
	  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" />

	<!-- /global stylesheets -->

	<!-- Core JS files -->
	<script src="{% static 'Labs/global_assets/js/main/jquery.min.js'%}"></script>
	<script src="{% static 'Labs/global_assets/js/main/bootstrap.bundle.min.js'%}"></script>
	<script src="{% static 'Labs/global_assets/js/plugins/loaders/blockui.min.js'%}"></script>
	<!-- /core JS files -->

	<!-- Theme JS files -->
	<script src="{% static 'Labs/global_assets/js/plugins/visualization/d3/d3.min.js'%}"></script>
	<script src="{% static 'Labs/global_assets/js/plugins/visualization/d3/d3_tooltip.js'%}"></script>
	<script src="{% static 'Labs/global_assets/js/plugins/forms/styling/switchery.min.js'%}"></script>
	<script src="{% static 'Labs/global_assets/js/plugins/forms/selects/bootstrap_multiselect.js'%}"></script>
	<script src="{% static 'Labs/global_assets/js/plugins/ui/moment/moment.min.js'%}"></script>
	<script src="{% static 'Labs/global_assets/js/plugins/pickers/daterangepicker.js'%}"></script>

	<script src="{% static 'Labs/assets/js/app.js'%}"></script>
	<script src="{% static 'Labs/global_assets/js/demo_pages/dashboard.js'%}"></script>

	<script src="{% static 'Labs/global_assets/js/plugins/notifications/pnotify.min.js' %}"></script>


	{% block header %}
	  
	{% endblock header %}
	<!-- /theme JS files -->

</head>

<body>

	<!-- Main navbar -->
	<div class="navbar navbar-expand-md navbar-dark">
		<div class="navbar-brand">
			<a href="{% if request.user.is_authenticated %}
			  /
			{% else %}
			/	  
			{% endif %}
			" class="d-inline-block">
				<i class="icon-atom2 mr-2 mb-1" style="font-size: 25px;"></i> Covid-19 System
			</a>
		</div>

		<div class="d-md-none">
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
				<i class="icon-tree5"></i>
			</button>
			<button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
				<i class="icon-paragraph-justify3"></i>
			</button>
		</div>

		<div class="collapse navbar-collapse " id="navbar-mobile">
			<ul class="navbar-nav ml-md-3 mr-md-auto">
				<li class="nav-item">
					<a href="#" class="navbar-nav-link sidebar-control sidebar-main-toggle d-none d-md-block">
						<i class="icon-paragraph-justify3"></i>
					</a>
				</li>

			</ul>


			<ul class="navbar-nav">

				<li class="nav-item" >
					{% if request.user.is_authenticated %}
					<a href="{% url 'Labs:logout_user' %}" style="color: rgb(252, 252, 252);" class="nav-link"><i class="icon-switch2"></i> Logout</a>					
					{% else %}
					<a href="{% url 'Labs:login_user' %}" style="color: rgb(252, 252, 252);" class="nav-link"><i class="icon-user"></i> Login</a>
					  
					{% endif %}
					
				</li>
			</ul>
		</div>
	</div>
	<!-- /main navbar -->

	<div class="page-content">
		<!-- Main sidebar -->
		
		{% if request.user.is_authenticated %}
		<div class="sidebar sidebar-dark sidebar-main sidebar-expand-md">
			<!-- Sidebar mobile toggler -->
			<div class="sidebar-mobile-toggler text-center">
				<a href="#" class="sidebar-mobile-main-toggle">
					<i class="icon-arrow-left8"></i>
				</a>
				Navigation
				<a href="#" class="sidebar-mobile-expand">
					<i class="icon-screen-full"></i>
					<i class="icon-screen-normal"></i>
				</a>
			</div>
			<!-- Sidebar content -->
			<div class="sidebar-content">
				<!-- Main navigation -->
				<div class="card card-sidebar-mobile">
					<ul class="nav nav-sidebar" data-nav-type="accordion">

						<!-- Main -->
						<li class="nav-item-header"><div class="text-uppercase font-size-xs line-height-xs">Main</div> <i class="icon-menu" title="Main"></i></li>
						<li class="nav-item">
							<a href="/" class="nav-link active">
								<i class="icon-home4"></i>
								<span>
									Dashboard
								</span>
							</a>
						</li>
						<li class="nav-item nav-item-submenu">
							<a href="#" class="nav-link"><i class="icon-user-tie"></i> <span>Lab Officials</span></a>

							<ul class="nav nav-group-sub" data-submenu-title="Layouts">
								<li class="nav-item"><a href="{% url 'Labs:register_tester' %}" class="nav-link"><i class="icon-user-plus"></i> Register Tester</a></li>
								<li class="nav-item"><a href="{% url 'Labs:tester_list' %}" class="nav-link"> <i class="icon-list-unordered"></i> View Testers</a></li>
							</ul>
						</li>
						<li class="nav-item nav-item-submenu">
							<a href="#" class="nav-link"><i class="icon-user"></i> <span>Patients</span></a>

							<ul class="nav nav-group-sub" data-submenu-title="Layouts">
								<li class="nav-item"><a href="{% url 'Labs:register_patient' %}" class="nav-link"><i class="icon-user-plus"></i> Register Patient</a></li>
								<li class="nav-item"><a href="{% url 'Labs:patient_list' %}" class="nav-link"> <i class="icon-list-unordered"></i> View patients</a></li>
							</ul>
						</li>

						<li class="nav-item nav-item-submenu">
							<a href="#" class="nav-link"><i class="icon-lab"></i> <span>Samples</span></a>

							<ul class="nav nav-group-sub" data-submenu-title="Themes">
								<li class="nav-item"><a href="{% url 'Labs:register_sample' %}" class="nav-link active"><i class="icon-plus-circle2"></i>Register Sample</a></li>
								<li class="nav-item"><a href="{% url 'Labs:sample_list' %}" class="nav-link"><i class="icon-list-unordered"></i> View Samples</a></li>
							</ul>
						</li>
						<li class="nav-item nav-item-submenu">
							<a href="#" class="nav-link"><i class="icon-aid-kit"></i> <span>Vaccination</span></a>

							<ul class="nav nav-group-sub" data-submenu-title="Themes">
								<li class="nav-item"><a href="{% url 'Labs:register_vaccination' %}" class="nav-link active"><i class="icon-plus-circle2"></i>New Patient</a></li>
								<li class="nav-item"><a href="{% url 'Labs:vaccination_list' %}" class="nav-link"><i class="icon-list-unordered"></i> View All</a></li>
							</ul>
						</li>
						<li class="nav-item nav-item-submenu">
							<a href="#" class="nav-link"><i class="icon-stats-dots"></i> <span>Reports</span></a>

							<ul class="nav nav-group-sub" data-submenu-title="Themes">
								<li class="nav-item"><a href="{% url 'Labs:infection_per_county' %}" class="nav-link active"><i class="icon-plus-circle2"></i>Infection per county</a></li>
								<li class="nav-item"><a href="{% url 'Labs:vaccination_list' %}" class="nav-link"><i class="icon-man-woman"></i> Infection Per Gender</a></li>
							</ul>
						</li>
					</ul>
				</div>
				<!-- /main navigation -->

			</div>
			<!-- /sidebar content -->
		</div>
		{% endif %}

		<!-- Main content -->
		<div class="content-wrapper">
		{%if messages%}
        {% for message in messages %}
			<script>
				var Pnotify = function() {

					var _componentPnotify = function() {
						if (typeof PNotify == 'undefined') {
							console.warn('Warning - pnotify.min.js is not loaded.');
							return;
						}
					}
					$(document).ready(function() {
						new PNotify({
							title: 'Message notice',
							text: '{{message}}',
							addclass: 'bg-{{message.tags}} border-success'
						});
						});
						return {
						init: function() {
							_componentPnotify();
						}
					}
				}();
				document.addEventListener('DOMContentLoaded', function() {
					Pnotify.init();
				});

			</script>
			{%endfor%}
			{%endif%}
			{% block body %}
			  
			{% endblock body %}
			<!-- Footer -->
			<div class="navbar navbar-expand-lg navbar-light">
				<div class="text-center d-lg-none w-100">
					<button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-footer">
						<i class="icon-unfold mr-2"></i>
						Footer
					</button>
				</div>

				<div class="navbar-collapse collapse" id="navbar-footer">
					<span class="navbar-text">
						&copy; 2021. <a href="#">Covid-19 System</a> by <a href="">PnJKenya</a>
					</span>

					<ul class="navbar-nav ml-lg-auto">
						<li class="nav-item"><a href="https://kopyov.ticksy.com/" class="navbar-nav-link" target="_blank"><i class="icon-lifebuoy mr-2"></i> Support</a></li>
						<li class="nav-item"><a href="http://demo.interface.club/limitless/docs/" class="navbar-nav-link" target="_blank"><i class="icon-file-text2 mr-2"></i> Docs</a></li>
						<li class="nav-item"><a href="https://themeforest.net/item/limitless-responsive-web-application-kit/13080328?ref=kopyov" class="navbar-nav-link font-weight-semibold"><span class="text-pink-400"><i class="icon-cart2 mr-2"></i> Purchase</span></a></li>
					</ul>
				</div>
			</div>
			<!-- /footer -->
		</div>
	</div>

<div class="modal fade" id="confirmDeleteModal" tabindex="-1" caller-id="" role="dialog"
    aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header text-center">
          <div class="container text-center">
            <h2 class="modal-title" id="">Terminate Lease</h2>
          </div>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">x</span>
          </button>
        </div>
        <div class="modal-body confirm-delete">
          <div class="container text-center">
            <i class="icon-warning" style="color:red; font-size: 50px;"></i><br>
            <span>Are you sure you want to Terminate this lease?</span><br>
            <h3>This action is permanent!</h3>
          </div>
        </div>
        <div class="modal-footer">
          <div class="container">
            <button style="float:left;" type="button" class="btn btn-primary btn-sm"
              data-dismiss="modal">Cancel</button>
            <button style="float:right;" type="button" class="btn btn-danger btn-sm" data-dismiss="modal"
              id="confirmDeleteButtonModal">Confirm</button>
          </div>
        </div>
      </div>
    </div>
</div>

	<script>
		$(document).on('click', '.confirm-delete', function () {
		  $("#confirmDeleteModal").attr("caller-id", $(this).attr("id"));
		});
	
		$(document).on('click', '#confirmDeleteButtonModal', function () {
		  var caller = $("#confirmDeleteButtonModal").closest(".modal").attr("caller-id");
		  window.location = $("#".concat(caller)).attr("href");
		});
	  </script>
	

	{% block scripts %}
	  
	{% endblock scripts %}
</body>
</html>